/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJavaConstructor */

#ifndef _Included_TestJavaConstructor
#define _Included_TestJavaConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJavaConstructor
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJavaConstructor_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
